export const ROUTES = {
  DASHBOARD: "/dashboard",
  PROJECTS: "/projects",
  PROJECT_DETAIL: (id: string) => `/projects/${id}`,
  PROJECT_SAFETY: (id: string) => `/projects/${id}/safety`,
  PROJECT_QUALITY: (id: string) => `/projects/${id}/quality`,
  PROJECT_WAREHOUSE: (id: string) => `/projects/${id}/warehouse`,
  PROJECT_BUDGET: (id: string) => `/projects/${id}/budget`,
  PROJECT_SETTINGS: (id: string) => `/projects/${id}/settings`,
  PROJECT_MEMBERS: (id: string) => `/projects/${id}/members`,
  PROJECT_REPORTS: (id: string) => `/projects/${id}/reports`,
  PROJECT_TASKS: (id: string) => `/projects/${id}/tasks`,
  PROJECT_FILES: (id: string) => `/projects/${id}/files`,
  PROJECT_DOCUMENTS: (id: string) => `/projects/${id}/documents`,
  DOCUMENT_SEARCH: "/documents/search",
  NOTIFICATIONS: "/notifications",
  USERS: "/users",
  APPROVALS: "/approvals",
  AUDIT_LOGS: "/audit-logs",
  SETTINGS: "/settings",
  SETTINGS_PROFILE: "/settings/profile",
  SETTINGS_CHANGE_PASSWORD: "/settings/change-password",
  FORGOT_PASSWORD: "/forgot-password",
  RESET_PASSWORD: (token: string) => `/reset-password/${token}`,
  LOGIN: "/login",
  ACCESS_DENIED: "/access-denied",
} as const;
